---

is_debug: true
listen:
  type: port
  bind_ip: 84.38.180.103
  port: 10003
mongodb:
  host: 127.0.0.1
  port: 27017
  username:
  password:
  auth_db: notes_system
  database: notes_system
  collection: notes